[package]
name = "n2"
version = "0.1.0"
categories = ["development-tools", "development-tools::build-utils"]
edition = "2018"
exclude = [".github/*", ".vscode/*"]
homepage = "https://github.com/evmar/n2"
keywords = ["ninja", "build"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/evmar/n2"
# std::thread::available_parallelism
rust-version = "1.59"
description = "a ninja compatible build system"

[dependencies]
anyhow = "1.0"
argh = "0.1.10"
lazy_static = "1.4.0"
libc = "0.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.6"
features = [
  "consoleapi",
  "errhandlingapi",
  "handleapi",
  "processenv",
  "processthreadsapi",
  "std",
  "synchapi",
  "winbase",
]

[target.'cfg(not(any(windows, target_arch = "wasm32")))'.dependencies]
jemallocator = "0.5.0"

[dev-dependencies]
tempfile = "3.6.0"

[profile.release]
debug = true
lto = true
