[package]
name = "n2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
anyhow = "1.0"
jemallocator = "0.3.2"

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "canon"
harness = false
